#!/usr/bin/env bash

NEXPORT_EXPORT_DIR="${HOME}/.nexport/exports"

_ensure_export_dir() {
  mkdir -p "$NEXPORT_EXPORT_DIR"
}

export_db() {
  local format="${1,,}"
  local timestamp
  timestamp=$(date +"%Y%m%d_%H%M%S")
  local outfile

  case "$format" in
    json)            outfile="${NEXPORT_EXPORT_DIR}/nexport_db_${timestamp}.json" ;;
    csv)             outfile="${NEXPORT_EXPORT_DIR}/nexport_db_${timestamp}.csv" ;;
    markdown|md)     outfile="${NEXPORT_EXPORT_DIR}/nexport_db_${timestamp}.md" ;;
    html)            outfile="${NEXPORT_EXPORT_DIR}/nexport_db_${timestamp}.html" ;;
    *)
      echo -e "\n  ${RED}Unknown format: ${format}${RESET}"
      echo -e "  ${YELLOW}Usage: export <json|csv|markdown|html>${RESET}\n"
      return
      ;;
  esac

  _ensure_export_dir

  echo -e "\n  ${CYAN}Exporting ${BOLD}${#PORT_DATA[@]}${RESET}${CYAN} ports to ${WHITE}${format^^}${CYAN}...${RESET}"

  case "$format" in
    json)            _export_json "$outfile" ;;
    csv)             _export_csv "$outfile" ;;
    markdown|md)     _export_markdown "$outfile" ;;
    html)            _export_html "$outfile" ;;
  esac

  if [[ -f "$outfile" ]]; then
    local size
    size=$(du -sh "$outfile" 2>/dev/null | cut -f1)
    echo -e "  ${GREEN}${OK} Export complete: ${WHITE}${outfile}${RESET}  ${DIM}(${size})${RESET}\n"
  else
    echo -e "  ${RED}${FAIL} Export failed — check permissions on ${NEXPORT_EXPORT_DIR}${RESET}\n"
  fi
}

_export_json() {
  local outfile="$1"
  local first=true
  echo "[" > "$outfile"

  for key in $(echo "${!PORT_DATA[@]}" | tr ' ' '\n' | sort -n); do
    local entry="${PORT_DATA[$key]}"
    IFS='|' read -r port name proto enc cat desc detail risk cves exploits <<< "$entry"
    detail="${detail//\"/\\\"}"
    desc="${desc//\"/\\\"}"

    $first || echo "," >> "$outfile"
    first=false

    cat >> "$outfile" << JSONENTRY
  {
    "port": $port,
    "name": "$name",
    "protocol": "$proto",
    "encrypted": "$enc",
    "category": "$cat",
    "description": "$desc",
    "detail": "$detail",
    "risk": "$risk",
    "cves": "$cves",
    "exploits": "$exploits"
  }
JSONENTRY
  done

  echo "]" >> "$outfile"
}

_export_csv() {
  local outfile="$1"
  echo "port,name,protocol,encrypted,category,description,risk,cves,exploits" > "$outfile"

  for key in $(echo "${!PORT_DATA[@]}" | tr ' ' '\n' | sort -n); do
    IFS='|' read -r port name proto enc cat desc detail risk cves exploits <<< "${PORT_DATA[$key]}"
    desc="${desc//\"/\"\"}"
    detail="${detail//\"/\"\"}"
    echo "\"$port\",\"$name\",\"$proto\",\"$enc\",\"$cat\",\"$desc\",\"$risk\",\"$cves\",\"$exploits\"" >> "$outfile"
  done
}

_export_markdown() {
  local outfile="$1"
  {
    echo "# NexPort v3.0 — Port Vulnerability Database Export"
    echo ""
    echo "> **Generated:** $(date)"
    echo "> **Total ports:** ${#PORT_DATA[@]}"
    echo "> **Tool:** NexPort v3.0 — Professional Network Port Intelligence"
    echo ""
    echo "## Port Reference Table"
    echo ""
    echo "| Port | Name | Protocol | Encrypted | Category | Risk | CVEs | Description |"
    echo "|------|------|----------|-----------|----------|------|------|-------------|"

    for key in $(echo "${!PORT_DATA[@]}" | tr ' ' '\n' | sort -n); do
      IFS='|' read -r port name proto enc cat desc detail risk cves exploits <<< "${PORT_DATA[$key]}"
      local cve_display="${cves:-—}"
      [[ "$cves" == "-" ]] && cve_display="—"
      echo "| $port | \`$name\` | $proto | $enc | $cat | **$risk** | $cve_display | $desc |"
    done

    echo ""
    echo "## Category Summary"
    echo ""
    declare -A cat_count
    for key in "${!PORT_DATA[@]}"; do
      IFS='|' read -r port name proto enc cat rest <<< "${PORT_DATA[$key]}"
      cat_count[$cat]=$(( ${cat_count[$cat]:-0} + 1 ))
    done

    echo "| Category | Port Count |"
    echo "|----------|------------|"
    for cat in "${!cat_count[@]}"; do
      echo "| $cat | ${cat_count[$cat]} |"
    done | sort -t'|' -k3 -rn

    echo ""
    echo "---"
    echo "*Generated by NexPort v3.0 — https://github.com/nexport*"
  } > "$outfile"
}

_export_html() {
  local outfile="$1"
  {
    cat << 'HTMLHEAD'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NexPort v3.0 — Port Database</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{background:#0a0a0f;color:#e0e0ff;font-family:'Courier New',monospace;padding:20px}
  h1{color:#00ffff;text-shadow:0 0 20px #00ffff;margin:20px 0 5px;font-size:2em}
  .subtitle{color:#666;margin-bottom:30px;font-size:.9em}
  table{width:100%;border-collapse:collapse;font-size:.85em}
  th{background:#0d0d1a;color:#00ffff;padding:10px;text-align:left;border-bottom:2px solid #00ffff33;position:sticky;top:0}
  tr:nth-child(even){background:#0d0d1a}
  tr:hover{background:#111128}
  td{padding:8px 10px;border-bottom:1px solid #1a1a2e;vertical-align:top}
  .port{color:#00ffff;font-weight:bold}
  .name{color:#ffffff;font-weight:bold}
  .risk-CRITICAL{color:#ff0000;font-weight:bold}
  .risk-HIGH{color:#ff4444;font-weight:bold}
  .risk-MEDIUM{color:#ffaa00}
  .risk-LOW{color:#44ff44}
  .enc-YES{color:#44ff44}
  .enc-NO{color:#ff4444}
  .enc-PARTIAL{color:#ffaa00}
  .cve{color:#ff6644;font-size:.8em}
  .desc{color:#aaa;font-size:.85em}
  .cat{color:#888;font-size:.8em;font-style:italic}
  .stats{display:flex;gap:30px;margin:15px 0 25px;flex-wrap:wrap}
  .stat{background:#0d0d1a;border:1px solid #00ffff33;padding:10px 20px;border-radius:4px}
  .stat-n{font-size:1.8em;color:#00ffff;font-weight:bold}
  .stat-l{color:#666;font-size:.8em}
  input{background:#0d0d1a;border:1px solid #00ffff44;color:#e0e0ff;padding:8px 15px;font-family:inherit;width:300px;margin-bottom:15px;border-radius:2px}
  input:focus{outline:none;border-color:#00ffff}
</style>
</head>
<body>
<h1>NexPort v3.0</h1>
HTMLHEAD

    echo "<p class='subtitle'>Port Vulnerability Intelligence Database — Exported $(date)</p>"
    echo "<input type='text' id='search' placeholder='Filter by port, name, category, CVE...' onkeyup='filterTable()'>"

    declare -A cat_count risk_count
    local cve_ports=0
    for key in "${!PORT_DATA[@]}"; do
      IFS='|' read -r port name proto enc cat desc detail risk cves exploits <<< "${PORT_DATA[$key]}"
      cat_count[$cat]=$(( ${cat_count[$cat]:-0} + 1 ))
      risk_count[$risk]=$(( ${risk_count[$risk]:-0} + 1 ))
      [[ -n "$cves" && "$cves" != "-" ]] && ((cve_ports++))
    done

    echo "<div class='stats'>"
    echo "  <div class='stat'><div class='stat-n'>${#PORT_DATA[@]}</div><div class='stat-l'>Total Ports</div></div>"
    echo "  <div class='stat'><div class='stat-n' style='color:#ff4444'>${risk_count[HIGH]:-0}</div><div class='stat-l'>High Risk</div></div>"
    echo "  <div class='stat'><div class='stat-n' style='color:#ffaa00'>${risk_count[MEDIUM]:-0}</div><div class='stat-l'>Medium Risk</div></div>"
    echo "  <div class='stat'><div class='stat-n' style='color:#ff6644'>${cve_ports}</div><div class='stat-l'>Ports with CVEs</div></div>"
    echo "  <div class='stat'><div class='stat-n'>${#cat_count[@]}</div><div class='stat-l'>Categories</div></div>"
    echo "</div>"

    echo "<table id='portTable'>"
    echo "<thead><tr><th>Port</th><th>Name</th><th>Protocol</th><th>Encrypted</th><th>Category</th><th>Risk</th><th>CVEs</th><th>Description</th></tr></thead>"
    echo "<tbody>"

    for key in $(echo "${!PORT_DATA[@]}" | tr ' ' '\n' | sort -n); do
      IFS='|' read -r port name proto enc cat desc detail risk cves exploits <<< "${PORT_DATA[$key]}"
      local cve_display="${cves}"
      [[ "$cves" == "-" || -z "$cves" ]] && cve_display="—"
      echo "<tr>"
      echo "  <td class='port'>$port</td>"
      echo "  <td class='name'>$name</td>"
      echo "  <td>$proto</td>"
      echo "  <td class='enc-${enc}'>$enc</td>"
      echo "  <td class='cat'>$cat</td>"
      echo "  <td class='risk-${risk}'>$risk</td>"
      echo "  <td class='cve'>$cve_display</td>"
      echo "  <td class='desc'>$desc</td>"
      echo "</tr>"
    done

    cat << 'HTMLFOOT'
</tbody>
</table>
<script>
function filterTable(){
  const v=document.getElementById('search').value.toLowerCase();
  const rows=document.querySelectorAll('#portTable tbody tr');
  rows.forEach(r=>{r.style.display=r.textContent.toLowerCase().includes(v)?'':'none'});
}
</script>
</body>
</html>
HTMLFOOT
  } > "$outfile"
}
